[package]
name = "adventu-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.12", features = ["canvas"] }
iced_style = "0.12"
rlua = "0.20"
rodio = "0.19"